// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLE7IFcek2aSQS_SWM0mHMMBDsIhFwjPc',
    appId: '1:243497263229:web:3c6ab53c76378c8e561114',
    messagingSenderId: '243497263229',
    projectId: 'liburan-app',
    authDomain: 'liburan-app.firebaseapp.com',
    storageBucket: 'liburan-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD02fbam74H8TE5IskSpRJeqqKU-I7Xb6E',
    appId: '1:243497263229:android:42c95a20044da29f561114',
    messagingSenderId: '243497263229',
    projectId: 'liburan-app',
    storageBucket: 'liburan-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGzqYUwSzSGfjHHnME1ZkH_u2ZZ_dHdE',
    appId: '1:243497263229:ios:de9f00797a5f2d5a561114',
    messagingSenderId: '243497263229',
    projectId: 'liburan-app',
    storageBucket: 'liburan-app.appspot.com',
    iosClientId: '243497263229-skjcd8366klkfei4up995jbvklgi2tdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.liburanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQGzqYUwSzSGfjHHnME1ZkH_u2ZZ_dHdE',
    appId: '1:243497263229:ios:de9f00797a5f2d5a561114',
    messagingSenderId: '243497263229',
    projectId: 'liburan-app',
    storageBucket: 'liburan-app.appspot.com',
    iosClientId: '243497263229-skjcd8366klkfei4up995jbvklgi2tdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.liburanApp',
  );
}
